library(sf)

setwd("/media/huijieqiao/Butterfly/rgee_greenhouse/rgee_greenhouse")
town<-st_read("../Shape/Towns/Towns.shp")
town_m<-st_transform(town, crs=st_crs("+proj=utm +zone=54 +south +datum=WGS84 +units=m +no_defs"))
grid<-st_make_grid(town_m, cellsize=50000, crs=st_crs(town_m))
length(grid)
#plot(grid)
country<-st_union(town_m)
country<-st_cast(country, "POLYGON")
areas<-st_area(country)
sf_country<-st_sf(AREA=areas, geometry=country)
sf_country<-sf_country[which(as.numeric(sf_country$AREA)>30000000000),]
plot(sf_country)
st_write(sf_country, "../Shape/Towns/China.shp", append = F)
plot(sf_country$geometry)
sf_country<-st_simplify(sf_country)
sf_country<-st_make_valid(sf_country)
overlap_index<-st_intersects(sf_country, grid)
overlap_index<-unlist(overlap_index)
grid_china<-grid[overlap_index]
length(grid_china)
#plot(grid_china)
grid_china_sf<-st_sf(ID=c(1:length(grid_china)), geometry=grid_china, crs=st_crs(grid_china))
st_write(grid_china_sf, "../Shape/Towns/grid_china.shp", append=F)
plot(grid_china_sf$geometry)
nrow(grid_china_sf)
